import { useEffect, useState } from 'react'
import { Button } from '../common/Button'
import { useInterviewSession } from '../../hooks/useInterviewSession'
import type { InterviewQuestion, ProgrammingLanguage } from '../../types/interview'

interface SolutionPanelProps {
  question: InterviewQuestion
  solution: string
  language: ProgrammingLanguage
  onLanguageChange: (language: ProgrammingLanguage) => void
  onClose: () => void
  isSolutionLoading?: boolean
  solutionError?: string
}

export const SolutionPanel = ({ 
  question, 
  solution, 
  language, 
  onLanguageChange, 
  onClose,
  isSolutionLoading = false,
  solutionError = ''
}: SolutionPanelProps) => {
  const { registerSubmission } = useInterviewSession()
  const [isConfirming, setIsConfirming] = useState(true)
  const [hasConfirmed, setHasConfirmed] = useState(false)
  const canConfirm = !solutionError

  const handleConfirmSolution = () => {
    if (!canConfirm) {
      return
    }
    setHasConfirmed(true)
    setIsConfirming(false)
  }

  const handleCancelSolution = () => {
    setIsConfirming(false)
    onClose()
  }

  useEffect(() => {
    if (!hasConfirmed) {
      return
    }
    if (!solution || solutionError) {
      return
    }
    // Register submission with 0 score for viewing solution
    registerSubmission({ passed: true, awardedScore: 0 })
    setHasConfirmed(false)
  }, [hasConfirmed, registerSubmission, solution, solutionError])

  return (
    <>
      <div className="h-full bg-white rounded-lg shadow-lg p-6 text-slate-900">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold">Approach</h3>
          <Button variant="ghost" size="sm" onClick={onClose}>
            Close
          </Button>
        </div>
        <div className="space-y-4">
          {isConfirming ? (
            <div className="rounded-lg border border-amber-200/60 bg-amber-50 p-4 text-sm text-amber-700">
              If you view the approach (solution), you will receive 0 score for this question.
            </div>
          ) : isSolutionLoading ? (
            <div className="bg-gray-50 p-4 rounded-lg">
              <div className="flex items-center gap-3">
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-gray-300 border-t-blue-500"></div>
                <span className="text-sm font-medium text-gray-600">Fetching approach...</span>
              </div>
            </div>
          ) : solutionError ? (
            <div className="bg-red-50 p-4 rounded-lg border border-red-200">
              <h4 className="font-semibold mb-2 text-red-600">Error Loading Approach</h4>
              <p className="text-sm text-red-500">{solutionError}</p>
            </div>
          ) : solution ? (
            <div className="bg-gray-50 p-4 rounded-lg">
              <h4 className="font-semibold mb-2">Approach:</h4>
              <pre className="text-sm whitespace-pre-wrap">
                {solution}
              </pre>
            </div>
          ) : (
            <div className="bg-gray-50 p-4 rounded-lg">
              <h4 className="font-semibold mb-2">No Approach Available</h4>
              <p className="text-sm text-gray-600">The approach is not available for this question.</p>
            </div>
          )}
          <div className="text-sm text-gray-600">
            This approach was generated by our AI assistant to help you understand the problem better.
          </div>
        </div>
      </div>

      {isConfirming && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 max-w-md w-full mx-4">
            <h3 className="text-lg font-semibold mb-2">View Approach</h3>
            {isSolutionLoading ? (
              <div className="mb-6 flex items-center gap-3 rounded-md border border-blue-100 bg-blue-50 px-3 py-2 text-sm text-blue-700">
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-blue-200 border-t-blue-600"></div>
                <span>Fetching approach...</span>
              </div>
            ) : solutionError ? (
              <div className="mb-6 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-600">
                {solutionError}
              </div>
            ) : (
              <p className="text-gray-600 mb-6">
                Are you sure? If you see the approach, you will receive 0 score for this question.
              </p>
            )}
            <div className="flex justify-end space-x-3">
              <Button variant="ghost" onClick={handleCancelSolution}>
                Cancel
              </Button>
              <Button
                onClick={handleConfirmSolution}
                disabled={!canConfirm}
                className="bg-red-500 hover:bg-red-600 text-white disabled:cursor-not-allowed disabled:opacity-70"
              >
                View Approach
              </Button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
